# Generated by Django 3.2.6 on 2021-10-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0010_alter_contact_prof_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firt_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('year_graduated', models.IntegerField(null=True)),
                ('course_graduated', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('current_job', models.CharField(max_length=100)),
                ('current_employer', models.CharField(max_length=100)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
