# Generated by Django 3.2.6 on 2021-10-15 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0011_alumni'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumni',
            old_name='firt_name',
            new_name='first_name',
        ),
    ]
