# Generated by Django 3.2.6 on 2021-10-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0012_rename_firt_name_alumni_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
    ]
