# Generated by Django 3.2.6 on 2021-10-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0013_alter_alumni_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
