# Generated by Django 4.0.2 on 2022-02-01 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0014_alter_alumni_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='prof_id',
        ),
        migrations.DeleteModel(
            name='List',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
