# Generated by Django 4.0.2 on 2022-02-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0015_remove_contact_prof_id_delete_list_delete_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='course_graduated',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='current_employer',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='current_job',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='year_graduated',
        ),
        migrations.AddField(
            model_name='alumni',
            name='age',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
